VERSION:
  VER: "0.0.5"
  API_V1_STR: "/api/v1"
  API_PROJECT_NAME: "CS Chatbot API"
  PACKAGE_VERSION: "1.0.0"

PATHS:
  APRIORI_RECOMMENDATIONS: "recommendation_objects/apriori_recommendations.json"
  POPULARITY_RECOMMENDATIONS: "recommendation_objects/popularity_recommendation.csv"
  MENU_ITEMS: "other_objects/menu_items.csv"

AGENTS:
  GUARD_AGENT:
    NUMBER_OF_MESSAGES_TO_LOOK_BACK: 5

ROUTES:
  DESCRIPTION: "/description"
  DESC_TAG: "ProjectDescription"
  ORDER_TAKING: "/order_taking"
  ORDER_TAKING_TAG: "OrderTaking"

# LOGGING
LOGGING:
  LOG_DIR: "./logs"
  # LOG_FILE: "./logs/local_logs.log"
  # LOG_LEVEL: "DEBUG"
  # LOG_LEVEL: "INFO"
  # LOG_FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
